
Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-16.04"
  config.vm.box_version="201708.22.0"
  config.vm.provision :shell, path: "bootstrap.sh"
end

#Vagrant.configure("2") do |config|
#  config.vm.box = "hashicorp/precise64"
#  config.vm.box_version="1.1.0"
#  config.vm.provision :shell, path: "bootstrap.sh"
#  config.vm.network :forwarded_port, guest: 80, host: 4567
#end
